# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-25 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190525_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamrecord',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
