# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190525_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='a task', max_length=255),
            preserve_default=False,
        ),
    ]
