# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to do', 'to do'), ('done', 'done'), ('in progress', 'in progress'), ('to be corrected', 'to be corrected')], default='to do', max_length=10),
        ),
    ]
