# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-26 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190526_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrecord',
            name='member',
        ),
    ]
